export const LOAD_SCREENSHOT_SUCCESS = "LOAD_SCREENSHOT_SUCCESS";
export const LOAD_SCREENSHOT = "LOAD_SCREENSHOT";
export const REMOVE_SCREENSHOT = "REMOVE_SCREENSHOT";
export const LOAD_SCREENSHOT_ERROR = "LOAD_SCREENSHOT_ERROR";
